# mkdocs: https://www.mkdocs.org/user-guide/configuration/
# MkDocs-Shadcn: https://www.mkdocs-shadcn.org/reference/admonitions
# mkdocstrings: https://mkdocstrings.github.io/usage/


site_name: steelsnakes
site_description: A Python library for structural steel.
site_author: Wayne Maranga
site_url: https://steelsnakes.readthedocs.io/en/latest/

repo_name: steelsnakes
repo_url: https://github.com/waynemaranga/steelsnakes
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Wayne Maranga

theme:
  name: shadcn
  show_title: true # show the title in the top bar
  show_stargazers: true # show the stargazers in the top bar
  pygments_style: # https://pygments.org/styles/
        light: abap
        dark: monokai
  icon: "heroicons:arrows-pointing-out" # https://heroicons.com/solid # use the shadcn svg if not defined
  topbar_sections: false # Keep sections in sidebar for better nested navigation
  katex_options: # optional
    macros: # example of macros
      "\\RR": "\\mathbb{R}" 
      "\\dx": "\\mathrm{d}x"
  show_datetime: false 
  # language: en
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - toc.follow
    - toc.integrate


plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            members_order: source
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
            filters: ["!^_"]
            heading_level: 1
  # - mike: # FIXME: One day review this and fix...
  #     # https://github.com/jimporter/mike?tab=readme-ov-file#usage
  #     alias_type: symlink
  #     version_selector: true

  - autorefs


markdown_extensions:
  admonition:
  codehilite:
  fenced_code:
  footnotes:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/waynemaranga/steelsnakes
    - icon: fontawesome/brands/python  
      link: https://pypi.org/project/steelsnakes/
    - icon: fontawesome/solid/envelope
      link: mailto:wayne.maranga@gmail.com
  


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  # - Overview:
  #   - What is SteelSnakes?: 01-overview/what-is-steelsnakes.md
  # - Getting Started:
  #   - Installation: 02-getting-started/installation.md
  #   - Quick Start: 02-getting-started/quickstart.md
  #   - Basic Usage: 02-getting-started/basic-usage.md
  # - User Guide:
  #   - Section Types: 03-user-guide/sections.md
  #   - Database System: 03-user-guide/database.md
  #   - Factory Pattern: 03-user-guide/factory.md
  #   - Search & Filtering: 03-user-guide/search.md
  # - Examples:
  #   - Basic Examples: 04-examples/basic.md
  #   - Advanced Usage: 04-examples/advanced.md
  #   - Steel Design: 04-examples/design.md
  # - API Reference:
  #   - Overview: 05-api-reference/index.md
  #   - Core Components:
  #     - Base Classes: 05-api-reference/core/base.md
  #     - Database System: 05-api-reference/core/database.md
  #     - Factory Pattern: 05-api-reference/core/factory.md
  #   - Regional Sections:
  #     - UK (British):
  #       - Overview: 05-api-reference/regional/UK/index.md
  #       - Universal Sections: 05-api-reference/regional/UK/universal/index.md
  #       - Channels: 05-api-reference/regional/UK/channels/index.md
  #       - Angles: 05-api-reference/regional/UK/angles/index.md
  #       - Hollow Sections: 05-api-reference/regional/UK/hollow/index.md
  #       - Connections: 05-api-reference/regional/UK/connections/index.md
  #     - US (American): 05-api-reference/regional/US/index.md
  #     - EU (European): 05-api-reference/regional/EU/index.md
  #     - AU (Australian): 05-api-reference/regional/AU/index.md
  #     - IN (Indian): 05-api-reference/regional/IS/index.md
  
  # - Contributing: contributing.md
  # - Changelog: changelog.md
