# mkdocs: https://www.mkdocs.org/user-guide/configuration/
# MkDocs-Shadcn: https://www.mkdocs-shadcn.org/reference/admonitions
# mkdocstrings: https://mkdocstrings.github.io/usage/


site_name: steelsnakes
site_description: A Python library for structural steel.
site_author: Wayne Maranga
site_url: https://steelsnakes.readthedocs.io/en/latest/

repo_name: steelsnakes
repo_url: https://github.com/waynemaranga/steelsnakes
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Wayne Maranga

theme:
  name: shadcn
  show_title: true # show the title in the top bar
  show_stargazers: true # show the stargazers in the top bar
  pygments_style: # https://pygments.org/styles/
        light: abap
        dark: monokai
  icon: "heroicons:arrows-pointing-out" # https://heroicons.com/solid # use the shadcn svg if not defined
  topbar_sections: false # Keep sections in sidebar for better nested navigation
  katex_options: # optional
    macros: # example of macros
      "\\RR": "\\mathbb{R}" 
      "\\dx": "\\mathrm{d}x"
  show_datetime: false 
  # language: en
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - toc.follow
    - toc.integrate


plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            members_order: source
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
            filters: ["!^_"]
            heading_level: 1
  # - mike: # FIXME: One day review this and fix...
  #     # https://github.com/jimporter/mike?tab=readme-ov-file#usage
  #     alias_type: symlink
  #     version_selector: true

  - autorefs


markdown_extensions:
  admonition:
  codehilite:
  fenced_code:
  footnotes:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha: # probably built-in
  shadcn.extensions.codexec: # probably built-in

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/waynemaranga/steelsnakes
    - icon: fontawesome/brands/python  
      link: https://pypi.org/project/steelsnakes/
    - icon: fontawesome/solid/envelope
      link: mailto:wayne.maranga@gmail.com
  


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Guides: 
    - First Steps: 01-guides/index.md
    - Codes and Standards: 01-guides/03-codesandstds.md
  - API Reference: 02-api-reference/index.md
