"""BS 5950-1:2000 checks; legacy, since many people still use it anyway...

BS 5950 designs with the same rolled profiles as the UK module (BS 4-1 ~ BS EN 10365), so the UK section constructors
are re-exported here: `from steelsnakes.BS import UB, classify_section, check_bending`.

- steelsnakes.BS.checks.classification: Section 3.5 classification and the effective plastic modulus (3.5.6)
- steelsnakes.BS.checks.uls: ultimate limit states, Sections 2.4, 3.4, 3.6 and 4 with Annexes B, C, H and I
- steelsnakes.BS.checks.sls: serviceability limit states, 2.5
"""

from steelsnakes.BS.checks import (
    CLASS_NAMES,
    ClassificationResult,
    EffectivePlasticModulusResult,
    ElementClassification,
    ElementInput,
    ElementKind,
    ElementLimits,
    ElementStressDistribution,
    StressPattern,
    StressRatios,
    classify_element,
    classify_elements,
    classify_section,
    classify_section_from_dict,
    compound_flange_elements,
    design_strength,
    effective_plastic_modulus,
    effective_plastic_modulus_chs,
    effective_plastic_modulus_i_section,
    effective_plastic_modulus_rhs,
    element_limits,
    epsilon,
    render_classification,
    stress_ratios,
    beam_effective_length,
    bending_strength,
    cantilever_effective_length,
    check_angle_strut,
    check_beam_deflection,
    check_bending,
    check_brittle_fracture,
    check_compression,
    check_compression_and_bending,
    check_horizontal_deflection,
    check_lateral_torsional_buckling,
    check_shear,
    check_simple_column,
    check_single_angle_compression_and_bending,
    check_sway_stability,
    check_tension,
    check_tension_and_bending,
    check_vertical_deflection,
    check_vibration,
    check_web_bearing,
    compressive_strength,
    effective_length,
    effective_section,
    equivalent_uniform_moment_factor_m,
    equivalent_uniform_moment_factor_mLT,
    factored_load,
    net_area,
    serviceability_load,
)
from steelsnakes.UK.sections.angles import L_EQUAL, L_EQUAL_B2B, L_UNEQUAL, L_UNEQUAL_B2B
from steelsnakes.UK.sections.cf_hollow import CFCHS, CFRHS, CFSHS
from steelsnakes.UK.sections.channels import PFC
from steelsnakes.UK.sections.hf_hollow import HFCHS, HFRHS, HFSHS
from steelsnakes.UK.sections.universal import UB, UBP, UC

__all__: list[str] = [
    # Checks; classification, Section 3.5
    "CLASS_NAMES",
    "ClassificationResult",
    "EffectivePlasticModulusResult",
    "ElementClassification",
    "ElementInput",
    "ElementKind",
    "ElementLimits",
    "ElementStressDistribution",
    "StressPattern",
    "StressRatios",
    "classify_element",
    "classify_elements",
    "classify_section",
    "classify_section_from_dict",
    "compound_flange_elements",
    "design_strength",
    "effective_plastic_modulus",
    "effective_plastic_modulus_chs",
    "effective_plastic_modulus_i_section",
    "effective_plastic_modulus_rhs",
    "element_limits",
    "epsilon",
    "render_classification",
    "stress_ratios",
    # Checks; ultimate limit states, Sections 2.4, 3.4, 3.6 and 4
    "factored_load",
    "check_sway_stability",
    "check_brittle_fracture",
    "net_area",
    "effective_section",
    "check_shear",
    "check_bending",
    "beam_effective_length",
    "cantilever_effective_length",
    "equivalent_uniform_moment_factor_mLT",
    "bending_strength",
    "check_lateral_torsional_buckling",
    "check_web_bearing",
    "check_tension",
    "effective_length",
    "compressive_strength",
    "check_compression",
    "check_angle_strut",
    "check_simple_column",
    "equivalent_uniform_moment_factor_m",
    "check_tension_and_bending",
    "check_compression_and_bending",
    "check_single_angle_compression_and_bending",
    # Checks; serviceability limit states, 2.5
    "serviceability_load",
    "check_vertical_deflection",
    "check_beam_deflection",
    "check_horizontal_deflection",
    "check_vibration",
    # Sections; from the UK module
    "UB",
    "UC",
    "UBP",
    "PFC",
    "L_EQUAL",
    "L_UNEQUAL",
    "L_EQUAL_B2B",
    "L_UNEQUAL_B2B",
    "HFCHS",
    "HFRHS",
    "HFSHS",
    "CFCHS",
    "CFRHS",
    "CFSHS",
]
