# AISC 360-22 checks in SI units (N, mm, MPa) for the US_Metric sections
# NOTE: the SI dispatchers and wrappers live in classification.py (B4.1) and members.py (C to H); the functions re-exported
# ... from steelsnakes.US.checks below have no unit-dependent constants, so they hold in N, mm and MPa as they are.
from steelsnakes.US.checks.classification import (
    ClassificationContext,
    CompressionCase,
    ElementClassification,
    ElementInput,
    FlexureCase,
    classify_compression,
    classify_flexure,
)
from steelsnakes.US.checks.tension import (
    PinConnectedMemberResult,
    ShearLagCase,
    TensionResult,
    calculate_effective_net_area,
    check_tension_slenderness,
    shear_lag_factor,
    tension_utilisation,
)
from steelsnakes.US.checks.compression import (
    CompressionResult,
    check_compression_slenderness,
    compression_utilisation,
    effective_length,
)
from steelsnakes.US.checks.flexure import (
    BendingAxis,
    FlexureResult,
    calculate_Cb,
    flexure_utilisation,
)
from steelsnakes.US.checks.shear import (
    ShearResult,
    shear_utilisation,
)
from steelsnakes.US.checks.combined import (
    TorsionResult,
    check_axial_flexure_interaction,
    check_flange_rupture_interaction,
    check_hss_combined_torsion,
    check_non_hss_torsion,
    check_out_of_plane_interaction,
    check_stress_interaction,
)
from steelsnakes.US.checks.stability import (
    ALPHA_ASD,
    ALPHA_LRFD,
    DesignMethod,
    ReducedStiffness,
    SecondOrderResult,
    amplified_required_strengths,
    calculate_B1,
    calculate_B2,
    calculate_Cm,
    calculate_Pe_story,
    calculate_RM,
    effective_length_method_permitted,
    first_order_additional_lateral_load,
    k_equals_one_permitted,
    notional_load,
    notional_loads,
    notional_loads_required_with_lateral_loads,
    p_delta_negligible,
    reduced_stiffness,
    stiffness_reduction_tau_b,
    tau_b_notional_load,
)
from steelsnakes.US_Metric.checks.classification import (
    E_STEEL,
    FU_A992,
    FY_A992,
    G_STEEL,
    METRIC_SCALE,
    ClassificationResult,
    classify_section,
    classify_section_from_dict,
    metric_properties,
    to_mm_units,
)
from steelsnakes.US_Metric.checks.members import (
    BETA_W_ANGLES_MM,
    EYEBAR_FY_LIMIT,
    EYEBAR_HOLE_CLEARANCE,
    EYEBAR_T_MIN,
    HOLE_ALLOWANCE,
    PIN_BE_OFFSET,
    PIN_CLEARANCES,
    REDISTRIBUTION_FY_LIMIT,
    angle_beta_w,
    calculate_net_area,
    calculate_Pe1,
    calculate_Pey,
    check_eyebar,
    check_first_order_method,
    check_pin_connected_member,
    compression,
    flexure,
    hss_torsion,
    moment_redistribution_Lm,
    shear,
    tension,
)

__all__: list[str] = [
    # SI constants and section data
    "E_STEEL",
    "G_STEEL",
    "FY_A992",
    "FU_A992",
    "METRIC_SCALE",
    "metric_properties",
    "to_mm_units",
    # B4.1 Classification
    "ClassificationContext",
    "ClassificationResult",
    "CompressionCase",
    "FlexureCase",
    "ElementInput",
    "ElementClassification",
    "classify_section",
    "classify_section_from_dict",
    "classify_compression",
    "classify_flexure",
    # D. Tension
    "HOLE_ALLOWANCE",
    "PIN_BE_OFFSET",
    "PIN_CLEARANCES",
    "EYEBAR_T_MIN",
    "EYEBAR_HOLE_CLEARANCE",
    "EYEBAR_FY_LIMIT",
    "TensionResult",
    "PinConnectedMemberResult",
    "ShearLagCase",
    "shear_lag_factor",
    "calculate_net_area",
    "calculate_effective_net_area",
    "check_tension_slenderness",
    "check_pin_connected_member",
    "check_eyebar",
    "tension",
    "tension_utilisation",
    # E. Compression
    "CompressionResult",
    "effective_length",
    "check_compression_slenderness",
    "compression",
    "compression_utilisation",
    # F. Flexure
    "BETA_W_ANGLES_MM",
    "BendingAxis",
    "FlexureResult",
    "calculate_Cb",
    "angle_beta_w",
    "flexure",
    "flexure_utilisation",
    # G. Shear
    "ShearResult",
    "shear",
    "shear_utilisation",
    # H. Combined forces and torsion
    "TorsionResult",
    "hss_torsion",
    "calculate_Pey",
    "check_axial_flexure_interaction",
    "check_out_of_plane_interaction",
    "check_stress_interaction",
    "check_hss_combined_torsion",
    "check_non_hss_torsion",
    "check_flange_rupture_interaction",
    # C. Design for stability; Appendices 7 and 8
    "REDISTRIBUTION_FY_LIMIT",
    "ALPHA_LRFD",
    "ALPHA_ASD",
    "DesignMethod",
    "ReducedStiffness",
    "SecondOrderResult",
    "p_delta_negligible",
    "notional_load",
    "notional_loads",
    "notional_loads_required_with_lateral_loads",
    "stiffness_reduction_tau_b",
    "reduced_stiffness",
    "tau_b_notional_load",
    "effective_length_method_permitted",
    "k_equals_one_permitted",
    "first_order_additional_lateral_load",
    "check_first_order_method",
    "calculate_Cm",
    "calculate_Pe1",
    "calculate_B1",
    "calculate_RM",
    "calculate_Pe_story",
    "calculate_B2",
    "amplified_required_strengths",
    "moment_redistribution_Lm",
]
