"""
US-Metric Steel Sections Module; AISC shapes in SI units, with AISC 360-22 checks in N, mm and MPa.
"""

from steelsnakes.US_Metric.checks import (
    E_STEEL,
    G_STEEL,
    FY_A992,
    FU_A992,
    BendingAxis,
    ClassificationContext,
    ClassificationResult,
    CompressionResult,
    FlexureResult,
    ShearResult,
    TensionResult,
    TorsionResult,
    amplified_required_strengths,
    calculate_B1,
    calculate_B2,
    check_axial_flexure_interaction,
    check_hss_combined_torsion,
    classify_section,
    classify_section_from_dict,
    compression,
    compression_utilisation,
    flexure,
    flexure_utilisation,
    hss_torsion,
    notional_load,
    notional_loads,
    shear,
    shear_utilisation,
    stiffness_reduction_tau_b,
    tension,
    tension_utilisation,
)
from steelsnakes.US_Metric.sections import (
    angles,
    beams,
    channels,
    hollow,
    piles,
    pipes,
    tees
)

__all__: list[str] = [
    # Checks; AISC 360-22 in SI units
    "E_STEEL",
    "G_STEEL",
    "FY_A992",
    "FU_A992",
    "ClassificationContext",
    "ClassificationResult",
    "classify_section",
    "classify_section_from_dict",
    "tension",
    "compression",
    "flexure",
    "shear",
    "hss_torsion",
    "TensionResult",
    "CompressionResult",
    "FlexureResult",
    "ShearResult",
    "TorsionResult",
    "BendingAxis",
    "tension_utilisation",
    "compression_utilisation",
    "flexure_utilisation",
    "shear_utilisation",
    "check_axial_flexure_interaction",
    "check_hss_combined_torsion",
    # Stability; AISC 360-22 Chapter C and Appendix 8
    "notional_load",
    "notional_loads",
    "stiffness_reduction_tau_b",
    "calculate_B1",
    "calculate_B2",
    "amplified_required_strengths",
    # Section types
    "angles",
    "beams",
    "channels",
    "hollow",
    "piles",
    "pipes",
    "tees"
]
